apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.web.service.portName }}
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
  selector:
    app: {{ .Values.web.name }}
